#!/bin/sh

# Copyright 2024 TerseTS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A pre-commit hook that checks if a Zig library with bindings has errors.

# Fail the entire hook immediately if any of the executed commands fails.
set -e

# Set the profiles to use for all of the tools from Zig that supports it.
profiles="Debug ReleaseFast"

# Ensure that the following commands does not emit any errors or warnings.
# - Compilers: zig build, clang, gcc
# - Linters: zig fmt --check .
# - Tests: zig build test and python3 -m unittest
for profile in $profiles
do
    echo "Profile $profile"
    echo "Zig Build"
    zig build -Doptimize=$profile
    echo
    echo "Zig Build Test"
    zig build test -Doptimize=$profile
    echo
    echo "Zig Fmt Check"
    zig fmt --check .
    echo
    echo "C Header Compile"
    pushd bindings/c > /dev/null
    clang -Weverything tersets.h
    gcc -Wall -Wextra tersets.h
    popd > /dev/null 
    echo
    echo "Python Test"
    pushd bindings/python > /dev/null
    python3 -m unittest
    popd > /dev/null
done
