// Copyright 2026 TerseTS Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Provides functions for generating Zig code at build time.
//! Currently it is used to generate integration tests for TerseTS.

const std = @import("std");
const Io = std.Io;
const Writer = Io.Writer;
const Error = Writer.Error;

const tersets = @import("tersets.zig");
const Method = tersets.Method;
const generators = @import("tester/generators.zig");
const setups = @import("tester/setups.zig");

/// Generate multiple files with source code at build time.
pub fn main(init: std.process.Init) !void {
    const io = init.io;
    try generateSourceCode(io, "src/integration_tests.zig", buildIntegrationTests);
}

/// Generate a file at `output_path` with source code created by `code_generator` at build time.
fn generateSourceCode(io: Io, output_path: []const u8, code_generator: fn (writer: *Writer) Error!void) !void {
    const cwd = Io.Dir.cwd();
    const output_file = try cwd.createFile(io, output_path, .{});
    defer output_file.close(io);

    // The contents of the buffer is undefined as the writer overwrites.
    // 8192 was choosen as 1024, 4096, and 8192 was gennerally recommended online,
    // and 8192 seems to be the value used for BUFSIZ on many Linux distributions.
    var buffer: [8192]u8 = undefined;
    var file_writer = output_file.writer(io, &buffer);
    const writer = &file_writer.interface;
    try code_generator(writer);
}

/// Generate source code at for integration tests and write it to `writer` at build time.
fn buildIntegrationTests(writer: *Writer) !void {
    const header =
        \\// This file is generated by tester/codegen.zig and is not designed to be edited.
        \\const std = @import("std");
        \\const ArrayList = std.ArrayList;
        \\const testing = std.testing;
        \\
        \\const tersets = @import("tersets.zig");
        \\const setups = @import("tester/setups.zig");
        \\const generators = @import("tester/generators.zig");
        \\const tester_random = @import("tester/random.zig");
        \\const Method = tersets.Method;
        \\
        \\
    ;
    try writer.writeAll(header);

    for (std.enums.values(Method)) |method| {
        const configurations = setups.getConfiguration(method);
        const assert_function = setups.getAssertFunction(method);
        // An index is added to the test name instead of the configuration to not create very long names.
        for (configurations) |configuration| {
            for (generators.generator_names) |generator_name| {
                // The test allow compress() to return an UnsupportedInput error without failing the test
                // as some compression methods cannot handle all f64 values, however, compressing values
                // incorrectly is never acceptable, so any other error must always fail the test.
                const integration_test =
                    \\test "{s} using generator {s} and configuration {s}" {{
                    \\    const allocator = testing.allocator;
                    \\    const random = tester_random.getRandomGenerator();
                    \\   
                    \\    var uncompressed_values = ArrayList(f64).empty;
                    \\    defer uncompressed_values.deinit(allocator);
                    \\    try generators.{s}(allocator, &uncompressed_values, random);
                    \\   
                    \\    const configuration = "{s}";
                    \\    var compressed_values = tersets.compress(
                    \\        allocator,
                    \\        uncompressed_values.items,
                    \\        Method.{s},
                    \\        configuration,
                    \\    ) catch |err| switch (err) {{
                    \\        error.UnsupportedInput => return,
                    \\        else => return err,
                    \\    }};
                    \\    defer compressed_values.deinit(allocator);
                    \\   
                    \\    var decompressed_values = try tersets.decompress(
                    \\        allocator,
                    \\        compressed_values.items,
                    \\    );
                    \\    defer decompressed_values.deinit(allocator);
                    \\   
                    \\    try setups.{s}(allocator,
                    \\                   uncompressed_values.items,
                    \\                   decompressed_values.items,
                    \\                   configuration,
                    \\    );
                    \\}}
                    \\
                    \\
                ;
                try writer.print(integration_test, .{
                    @tagName(method),
                    generator_name,
                    configuration,
                    generator_name,
                    configuration,
                    @tagName(method),
                    assert_function,
                });
            }
        }
    }

    // The writer is manually flushed as Zig does not allow the try keywrod in a defer expression.
    try writer.flush();
}
