// Copyright 2026 TerseTS Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Provides functions for generating Zig code at build time.
/// Currently it is used to generate integration tests for TerseTS.

// https://matklad.github.io/2025/04/19/things-zig-comptime-wont-do.html
// https://codeberg.org/ifreund/zig-wayland
// https://github.com/castholm/zigglgen/tree/master
// https://ziggit.dev/t/generating-tests-at-comptime/6473

const std = @import("std");

// TODO: Integrate value generation for multiple types of time series.
// const generators = @import("tester/generators.zig");
// TODO: Allow tests to fail with an error during compression, incorrect compression is the only thing not allowed.
// TODO: finish configurations for all methods.
// TODO: Factor writing out into functions as much as possible.
// TODO: Move generating tests into a function to make it clear codegen is for other tasks as well.

// This file cannot be moved to the tester directory as Zig can only import files from
// the same directory or sub-directories and Method is needed to generate the tests.
const tersets = @import("tersets.zig");
const Error = tersets.Error;
const Method = tersets.Method;

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const cwd = std.Io.Dir.cwd();

    const integration_tests = try cwd.createFile(io, "src/integration_tests.zig", .{});
    defer integration_tests.close(io);

    var buffer: [8192]u8 = undefined; // The writer overwrites it anyway.
    var file_writer = integration_tests.writer(io, &buffer);
    const writer = &file_writer.interface;

    const header =
        \\ // This file is generated by tester/main.zig and is not designed to be edited.
        \\ const std = @import("std");
        \\ const ArrayList = std.ArrayList;
        \\ const testing = std.testing;
        \\
        \\ const tersets = @import("tersets.zig");
        \\ const generators = @import("tester/generators.zig");
        \\ const Method = tersets.Method;
        \\
        \\
    ;
    try writer.writeAll(header);

    for (std.enums.values(Method), 1..) |method, index| {
        const configurations = getConfiguration(method);
        for (configurations) |configuration| {
            std.debug.print("{} {s}\n", .{ method, configuration });
            const integration_test =
                \\ test "{s}_{d}" {{
                \\ const allocator = testing.allocator;
                \\ const random = generators.getRandomGenerator();
                \\
                \\ var uncompressed_values = ArrayList(f64).empty;
                \\ defer uncompressed_values.deinit(allocator);
                \\ try generators.generateRandomValues(allocator, &uncompressed_values, random);
                \\
                \\ const configuration = "{s}";
                \\ var compressed_values = try tersets.compress(
                \\     allocator,
                \\     uncompressed_values.items,
                \\     Method.{s},
                \\     configuration,
                \\ );
                \\ defer compressed_values.deinit(allocator);
                \\
                \\ var decompressed_values = try tersets.decompress(
                \\     allocator,
                \\     compressed_values.items,
                \\ );
                \\ defer decompressed_values.deinit(allocator);
                \\
                \\ try std.testing.expectEqualSlices(f64, uncompressed_values.items, decompressed_values.items);
                \\ }}
            ;
            try writer.print(integration_test, .{ @tagName(method), index, configuration, @tagName(method) });
        }
    }

    // try is not allowed in a defer expression.
    try writer.flush();
}

/// Returns
fn getConfiguration(method: Method) []const []const u8 {
    return switch (method) {
        .Uncompressed => &[_][]const u8{""},
        else => &[_][]const u8{},
    };
}
