 // This file is generated by tester/main.zig and is not designed to be edited.
 const std = @import("std");
 const testing = std.testing;

 const tersets= @import("tersets.zig");
 const Method = tersets.Method;

 test "Uncompressed_1" {
 const allocator = testing.allocator;
 const uncompressed_values = &[4]f64{ 19.0, 48.0, 48.0, 3.0 };

 const configuration = "";
 var compressed_values = try tersets.compress(
     allocator,
     uncompressed_values,
     Method.Uncompressed,
     configuration,
 );
 defer compressed_values.deinit(allocator);

 var decompressed_values = try tersets.decompress(
     allocator,
     compressed_values.items,
 );
 defer decompressed_values.deinit(allocator);

 try std.testing.expectEqualSlices(f64, uncompressed_values, decompressed_values.items);
 }