// This file is generated by tester/codegen.zig and is not designed to be edited.
const std = @import("std");
const ArrayList = std.ArrayList;
const testing = std.testing;

const tersets = @import("tersets.zig");
const setups = @import("tester/setups.zig");
const generators = @import("tester/generators.zig");
const tester_random = @import("tester/random.zig");
const Method = tersets.Method;

test "Uncompressed generateConstantValues configuration 1" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();

    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateConstantValues(allocator, &uncompressed_values, random);

    const configuration = "";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.Uncompressed,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);

    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);

    try setups.assertEqual(uncompressed_values.items, decompressed_values.items);
}

test "Uncompressed generateLinearValues configuration 1" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();

    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateLinearValues(allocator, &uncompressed_values, random);

    const configuration = "";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.Uncompressed,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);

    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);

    try setups.assertEqual(uncompressed_values.items, decompressed_values.items);
}

test "Uncompressed generateRandomValues configuration 1" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();

    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateRandomValues(allocator, &uncompressed_values, random);

    const configuration = "";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.Uncompressed,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);

    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);

    try setups.assertEqual(uncompressed_values.items, decompressed_values.items);
}
