// This file is generated by tester/codegen.zig and is not designed to be edited.
const std = @import("std");
const ArrayList = std.ArrayList;
const testing = std.testing;

const tersets = @import("tersets.zig");
const setups = @import("tester/setups.zig");
const generators = @import("tester/generators.zig");
const tester_random = @import("tester/random.zig");
const Method = tersets.Method;

test "Uncompressed using generator generateConstantValues and configuration " {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateConstantValues(allocator, &uncompressed_values, random);
   
    const configuration = "";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.Uncompressed,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertEqual(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "Uncompressed using generator generateLinearValues and configuration " {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateLinearValues(allocator, &uncompressed_values, random);
   
    const configuration = "";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.Uncompressed,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertEqual(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "Uncompressed using generator generateRandomValues and configuration " {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateRandomValues(allocator, &uncompressed_values, random);
   
    const configuration = "";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.Uncompressed,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertEqual(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMidrange using generator generateConstantValues and configuration {\"abs_error_bound\": 0.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateConstantValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMidrange,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMidrange using generator generateLinearValues and configuration {\"abs_error_bound\": 0.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateLinearValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMidrange,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMidrange using generator generateRandomValues and configuration {\"abs_error_bound\": 0.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateRandomValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMidrange,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMidrange using generator generateConstantValues and configuration {\"abs_error_bound\": 0.1}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateConstantValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.1}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMidrange,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMidrange using generator generateLinearValues and configuration {\"abs_error_bound\": 0.1}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateLinearValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.1}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMidrange,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMidrange using generator generateRandomValues and configuration {\"abs_error_bound\": 0.1}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateRandomValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.1}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMidrange,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMidrange using generator generateConstantValues and configuration {\"abs_error_bound\": 1.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateConstantValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 1.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMidrange,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMidrange using generator generateLinearValues and configuration {\"abs_error_bound\": 1.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateLinearValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 1.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMidrange,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMidrange using generator generateRandomValues and configuration {\"abs_error_bound\": 1.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateRandomValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 1.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMidrange,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMean using generator generateConstantValues and configuration {\"abs_error_bound\": 0.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateConstantValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMean,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMean using generator generateLinearValues and configuration {\"abs_error_bound\": 0.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateLinearValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMean,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMean using generator generateRandomValues and configuration {\"abs_error_bound\": 0.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateRandomValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMean,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMean using generator generateConstantValues and configuration {\"abs_error_bound\": 0.1}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateConstantValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.1}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMean,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMean using generator generateLinearValues and configuration {\"abs_error_bound\": 0.1}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateLinearValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.1}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMean,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMean using generator generateRandomValues and configuration {\"abs_error_bound\": 0.1}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateRandomValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 0.1}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMean,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMean using generator generateConstantValues and configuration {\"abs_error_bound\": 1.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateConstantValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 1.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMean,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMean using generator generateLinearValues and configuration {\"abs_error_bound\": 1.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateLinearValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 1.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMean,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

test "PoorMansCompressionMean using generator generateRandomValues and configuration {\"abs_error_bound\": 1.0}" {
    const allocator = testing.allocator;
    const random = tester_random.getRandomGenerator();
   
    var uncompressed_values = ArrayList(f64).empty;
    defer uncompressed_values.deinit(allocator);
    try generators.generateRandomValues(allocator, &uncompressed_values, random);
   
    const configuration = "{\"abs_error_bound\": 1.0}";
    var compressed_values = tersets.compress(
        allocator,
        uncompressed_values.items,
        Method.PoorMansCompressionMean,
        configuration,
    ) catch |err| switch (err) {
        error.UnsupportedInput => return,
        else => return err,
    };
    defer compressed_values.deinit(allocator);
   
    var decompressed_values = try tersets.decompress(
        allocator,
        compressed_values.items,
    );
    defer decompressed_values.deinit(allocator);
   
    try setups.assertWithinAbsoluteErrorBound(allocator,
                   uncompressed_values.items,
                   decompressed_values.items,
                   configuration,
    );
}

